(uiop:define-package cl-fp/all
  (:mix
   #:cl-fp/api
   #:cl-fp/egal
   #:cl-fp/null
   #:cl-fp/cons
   #:cl-fp/lazy
   #:cl-fp/pair
   #:cl-fp/map
   #:cl-fp/vec
   #:cl-fp/set
   #:cl-fp/lib
   #:cl)
  (:use-reexport
   #:cl-fp/api
   #:cl-fp/egal
   #:cl-fp/null
   #:cl-fp/cons
   #:cl-fp/lazy
   #:cl-fp/pair
   #:cl-fp/map
   #:cl-fp/vec
   #:cl-fp/set
   #:cl-fp/lib))
